export const DASHBOARD_DATA = {
  stats: {
    totalStudents: 320,
    activeStudents: 280,
    newAdmissions: 45,
    alumni: 150,
  },
  attendance: [
    { name: 'Jan', value: 65 },
    { name: 'Feb', value: 75 },
    { name: 'Mar', value: 85 },
    { name: 'Apr', value: 92 },
  ],
  performance: [
    { name: 'Week 1', open: 3.40, close: 3.55, low: 3.32, high: 3.68 },
    { name: 'Week 2', open: 3.55, close: 3.68, low: 3.45, high: 3.75 },
    { name: 'Week 3', open: 3.68, close: 3.72, low: 3.62, high: 3.82 },
    { name: 'Week 4', open: 3.72, close: 3.85, low: 3.70, high: 3.92 },
  ],
  notices: [
    { id: 1, text: 'Class Suspension on 25 April', type: 'warning' },
    { id: 2, text: 'Project Submission Deadline: 30 April', type: 'info' },
    { id: 3, text: 'CR Meeting at 1 PM Today', type: 'urgent' },
    { id: 4, text: 'Annual Tech Fest Registration Open', type: 'info' },
    { id: 5, text: 'Lab Renovation starting Monday', type: 'warning' },
  ],
  events: [
    { name: 'Tech Seminar on 28 April', icon: 'BookOpen' },
    { name: 'Workshop on IOT', icon: 'Cpu' },
    { name: 'Cultural Fest Next Week', icon: 'Music' },
  ],
  projects: [
    'AI Robotics Project',
    'Startup: GreenTech Solutions',
    'IOT Smart Campus',
    'Hackathon: 1st Prize',
  ],
  admissionsTrend: [
    { name: '2020', count: 40 },
    { name: '2021', count: 55 },
    { name: '2022', count: 48 },
    { name: '2023', count: 70 },
    { name: '2024', count: 45 },
  ],
  studentDistribution: [
    { name: '1st Year', value: 80, color: '#3b82f6' },
    { name: '2nd Year', value: 70, color: '#10b981' },
    { name: '3rd Year', value: 90, color: '#f59e0b' },
    { name: '4th Year', value: 80, color: '#8b5cf6' },
  ],
  leaderboard: [
    { rank: 1, name: 'Sadia Islam', score: 3.98, id: 'CST-502', avatar: 'SI', photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150' },
    { rank: 2, name: 'Ali Hossain', score: 3.92, id: 'CST-505', avatar: 'AH', photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150' },
    { rank: 3, name: 'Nusrat Jahan', score: 3.88, id: 'CST-512', avatar: 'NJ', photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150' },
    { rank: 4, name: 'Tanvir Ahmed', score: 3.82, id: 'CST-520', avatar: 'TA', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150' },
    { rank: 5, name: 'Fahim Faisal', score: 3.75, id: 'CST-525', avatar: 'FF', photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150' },
  ],
  faculty: {
    head: 'Prof. Kamal Uddin',
    email: 'cst@cpi.ac.bd',
    mobile: '+880 1712-345678',
    office: 'Room 203',
  },
  placements: [
    { name: 'Ariful Islam', company: 'Google', position: 'Software Engineer', year: '2022' },
    { name: 'Mousumi Akter', company: 'Brain Station 23', position: 'Web Developer', year: '2021' },
    { name: 'Rayan Ahmed', company: 'Therap BD', position: 'Product Designer', year: '2023' },
    { name: 'Jannatul Ferdous', company: 'Dynamic Solution', position: 'QA Engineer', year: '2022' },
    { name: 'Shuvo Hasan', company: 'Tiger IT', position: 'Backend dev', year: '2021' },
    { name: 'Kamal Pasha', company: 'Samsung R&D', position: 'Senior Dev', year: '2020' },
    { name: 'Nila Sultana', company: 'Grameenphone', position: 'Network Eng.', year: '2022' },
    { name: 'Zayed Khan', company: 'Pathao', position: 'System Admin', year: '2023' },
    { name: 'Tahmina Akter', company: 'Enosis Solutions', position: 'Software Engineer', year: '2023' },
    { name: 'Faisal Mahmud', company: 'Kona Software', position: 'Frontend Dev', year: '2022' },
    { name: 'Lopa Rahman', company: 'DataSoft', position: 'Junior dev', year: '2024' },
    { name: 'Sajid Islam', company: 'Robi Axiata', position: 'System Eng.', year: '2021' },
  ],
  jobSeekers: [
    { name: 'Emon Khan', skills: 'React, Node.js, Firebase', github: 'emon-git' },
    { name: 'Sara Tabassum', skills: 'UI/UX, Figma, Tailwind', github: 'sara-design' },
    { name: 'Imtiaz Ahmed', skills: 'Python, Django, PostgreSQL', github: 'imtiaz-dev' },
    { name: 'Nafisa Sultana', skills: 'Machine Learning, AI, Python', github: 'nafisa-ai' },
    { name: 'Kazi Mahbub', skills: 'App Dev, Flutter, Dart', github: 'kazi-flutter' },
    { name: 'Rimi Akter', skills: 'Java, Spring, MySQL', github: 'rimi-dev' },
    { name: 'Tanvir Hasan', skills: 'C++, Embedded, IoT', github: 'tanvir-iot' },
  ]
};
